name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src'
       
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
      
    - name: Install dependencies    
      run: npm install
      
    - name: Run Tests
      run: npm test
      
    - name: Docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
   
    - name: Docker build
      run: docker build . --file Dockerfile --tag rajputmarch2020/node-app:$GITHUB_SHA
      
    - name: Docker Push
      run: docker push "rajputmarch2020/node-app:$GITHUB_SHA"
